apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: capital-market
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  DB_HOST: "mysql-svc"
  DB_PORT: "3306"
  DB_NAME: "platform"
  DB_CHARSET: "utf8mb4"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  APP_TIMEZONE: "Asia/Jakarta"
