apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: capital-market
type: Opaque
stringData:
  DB_USER: "platform"
  DB_PASS: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION"
  APP_ENCRYPTION_KEY: "CHANGE_ME_BASE64_32BYTE_KEY"
